#!/bin/sh
# Wrapper script for extramonitor

source_dir="$(dirname "$0")"

printf "\
Extend right\n\
Extend left\n\
Disconnect\n\
Mirror\n\
Extend right 100\n\
Extend left 100\n" | dmenu -fn 'Noto Sans-13' -i -p "Monitor Configuration" | xargs -I % $source_dir/displays_options.sh "%" "$1" "$2"
